services:
- docker
env:
  global:
  - secure: fsYMbL/PhxsRmO64jRgkoOYi437N3VZfz+f2Rcm407w62p/Ec4T4ZSa89ndKvB7tsnG9BMfcErp7O4Ph5OyKECgDMBfmYCpJr8CE13HJKMmOnEKRyTT1ZFCj6/5VBJKaSLD6PC/KCNBlK7BKLOpsfn/SRZZ7WcmTylABCg7v8aE0MJotc74wSuPIjqt8zyEa1dJUTBDw6Qxvpf3xhx4JYRf45HapiW6b+C8wB38FqGc9ACSxKCBWPW9wlMpAgKRxl+EZenjsgQlUWT78sh20qMUU0NoAyxTw5Vwe2mjjByuDdjXKK0reWleFgl/ebHiNMWi0MuN7IhAZ+etxyWvInAMlIsjFzyuPhsyfdr+Ksb0kzPQ8NwFAE3jWEu6AArj23qR8xfQPbHfOqj6PJkYeB94nxsbQbMFzhRYSadcGFjechJ0o0WdCGwzE4t4Lo5ydYZh0QgSedNa/u3/fu4TgdFWn3vkjUhdR2fpwuVl1Xx72LPxRmhZ1SrGqx0x82+dFSlJ8KrI/T9IvdPz5rqNNWyaoop+H9U6XBeE1lkVn9+z54TjJcPlCQA/l1MAerg6nfj+I6i4MgoK5edTahjXK/cqdNQgW6RMlHZUeiVwrjvhV+6aDfmywJyYcELebt9Z9R9WtmsU56bluF2zuQfp7gjIzRuxAvAYvn1/LXY/BYIQ= #DOCKER_USER
  - secure: OjqMGkw3L6MgU/whJ3DC1AWiFtn3MrmrWJBa26ww1tkZEWrCFvynGG+vQi8AZ1B6g6P3grgIxdJG2VH/PMf32E3t6/9mxHEYwNL7v5mghv9oJSgAl4tjvzFQxas2ySK8g67zBwBFI9y8efbIehgEzgSGoV+LHKonWJOZu8vWglguwwCQtiQUAFnpf58NQ9XO+q+AxqJ/fOhxcfrp/XuijPTixNJiv1Lgq7QQ3QtGRClK8ixDFkhAUkA6PKhtutC3jrfa+I1BKbUT30Bb8fp3HZv2NhiEpqLOmLHKbWOgkfDemQKKl/i3uuK2/48gCU2zGclMmo12Re4DB0OrMJEzdEIa3g/co55aIqN1VGBjRkJ2qSm63+E3pZfGJ0fKqB+jkpC0vTql0Ws+FkmF64XSA/8ZWMDgnwpGoTROLlwkghV6904pmExAyiYCq4fMV3+8XvEfnYsYWiU3tFCaY3hQCmbWZPNELw2fqkz2cR22nn6bexfTBfsqsTR4HPfKjtP01CZC53tHk2kf3heZGnNKOEleZ9W5Z+ohGFy4vDISJZgan2d/Imb92DbQCZk+H3wRXEGRwuaHBBK1fHyksmf++LmuyAvwVd8ICgmBm7dfc5WD6G9PfhIH7n1KSDLEgif19WiR2Wl/M9cTZ7DOCs0iaezCp2cXM2NRjXLdk067H/Q= #DOCKER_PASS
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=dargmuesli/1generator
  - DOCKER_BUILDKIT=1
addons:
  apt:
    packages:
    - docker-ce
before_install:
- echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
- sudo service docker restart
script:
- docker build -t 1generator .
- docker build -t $REPO:$COMMIT .
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;
  fi`
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
notifications:
  email:
    on_success: change
    on_failure: change
